name: CI
on: [push]
jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: npm install
      - name: Run build
        run: npm build
      - name: Run unit tests
        run: npm run test:unit
  functional-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: npm install
      - name: Run build
        run: npm build
      - name: Run functional tests
        run: npm run test:functional